### DISCUSSION TITLE
Missing Python 3.12 in GitHub Actions for macOS and Windows

### DISCUSSION THREAD

**Discussion by ringsaturn** [messense/maturin-action#218] [Q&A] [answered]
Hi there,

I'm using this Github Action to build my project and I found built results are
different.

The full workflow is here: https://github.com/ringsaturn/go-cities.json/actions/runs/6434453497/workflow

- In Linux build, 3.12's wheel was built:
  https://github.com/ringsaturn/go-cities.json/actions/runs/6434453497/job/17473709812#step:3:283
  ```yaml
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: messense/maturin-action@v1
        with:
          manylinux: auto
          command: build
          args: --release -o dist --find-interpreter
          working-directory: citiespy
          # sccache: true
      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: citiespy/dist
  ```
- In macOS build,
  ```yaml
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: messense/maturin-action@v1
        with:
          command: build
          args: --release -o dist --target universal2-apple-darwin --interpreter 
          working-directory: citiespy
          # sccache: true
      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: citiespy/dist
  ```

  However from output logs there is no Python 3.12:

  ```
  Python version 3.10.13 was found in the local cache
  Python version 3.11.5 was found in the local cache
  Python version 3.7.17 was found in the local cache
  Python version 3.8.18 was found in the local cache
  Python version 3.9.18 was found in the local cache
  ```
- In Windows build:
  https://github.com/ringsaturn/go-cities.json/actions/runs/6434453497/job/17473710304
  ```yaml
  windows:
     runs-on: windows-latest
     steps:
       - uses: actions/checkout@v4
       - uses: messense/maturin-action@v1
         with:
           command: build
           args: --release -o dist --find-interpreter
           working-directory: citiespy
       - name: Upload wheels
         uses: actions/upload-artifact@v3
         with:
           name: wheels
           path: citiespy/dist
  ```
