### ISSUE TITLE
Current directory

### ISSUE THREAD

**Issue by AleCandido** [messense/maturin-action#11]
Sorry to fire such a *stupid* issue, but since `maturin` does not have many configurations (by design) I'm having a hard time in finding a way to run this action in a workflow, when the crate I want to compile is part of a workspace.

Indeed the action is failing with:
```
💥 maturin failed
  Caused by: Failed to parse Cargo.toml at Cargo.toml
  Caused by: missing field `package` at line 9 column 1
```
that happens because the `Cargo.toml` it is looking is the one of the workspace, rather than the one of the crate I would like to package.

Is it possible to get an option to use with `with:` in order to specify which directory (and thus which crate) to use?
Maybe I'm just too stupid, but I'm not finding a way to make an action run with a specific directory...

**Comment by messense** [comment]
You can pass `-m`/`--manifest-path` to a `Cargo.toml` that you want to package in `args`, for example

```yaml
- uses: messense/maturin-action@v1
  with:
    maturin-version: latest
    command: build
    args: --release -m path/to/Cargo.toml
```
