### ISSUE TITLE
Question: cross compile to manylinux: `aarch64-unknown-linux-gnu`

### ISSUE THREAD

**Issue by ritchie46** [messense/maturin-action#26]
Hi!

I am trying to cross compile polars to manylinux `aarch64`, but the pipeline fails with:

<details>
<summary>stacktrace</summary>
  process didn't exit successfully: `/home/runner/work/polars/polars/py-polars/target/release/build/zstd-sys-144b3faaf22a9632/build-script-build` (exit status: 1)
  --- stdout
  TARGET = Some("aarch64-unknown-linux-gnu")
  HOST = Some("x86_64-unknown-linux-gnu")
  CC_aarch64-unknown-linux-gnu = None
  CC_aarch64_unknown_linux_gnu = None
  TARGET_CC = None
  CC = None
  CROSS_COMPILE = None
  CFLAGS_aarch64-unknown-linux-gnu = None
  CFLAGS_aarch64_unknown_linux_gnu = None
  TARGET_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  CARGO_CFG_TARGET_FEATURE = Some("fp,neon,pmuv3")
  running: "aarch64-linux-gnu-gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-I" "zstd/lib/" "-I" "zstd/lib/common" "-I" "zstd/lib/legacy" "-fvisibility=hidden" "-DZSTD_LIB_DEPRECATED=0" "-DXXH_PRIVATE_API=" "-DZSTDLIB_VISIBILITY=" "-DZDICTLIB_VISIBILITY=" "-DZSTDERRORLIB_VISIBILITY=" "-DZSTD_LEGACY_SUPPORT=1" "-o" "/home/runner/work/polars/polars/py-polars/target/aarch64-unknown-linux-gnu/release/build/zstd-sys-0db46d8e29890f56/out/zstd/lib/common/error_private.o" "-c" "zstd/lib/common/error_private.c"
  running: "aarch64-linux-gnu-gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-I" "zstd/lib/" "-I" "zstd/lib/common" "-I" "zstd/lib/legacy" "-fvisibility=hidden" "-DZSTD_LIB_DEPRECATED=0" "-DXXH_PRIVATE_API=" "-DZSTDLIB_VISIBILITY=" "-DZDICTLIB_VISIBILITY=" "-DZSTDERRORLIB_VISIBILITY=" "-DZSTD_LEGACY_SUPPORT=1" "-o" "/home/runner/work/polars/polars/py-polars/target/aarch64-unknown-linux-gnu/release/build/zstd-sys-0db46d8e29890f56/out/zstd/lib/common/zstd_common.o" "-c" "zstd/lib/common/zstd_common.c"

  --- stderr

  error occurred: Failed to find tool. Is `aarch64-linux-gnu-gcc` installed?
</details>

This is my setup. Any ideas? 

```yaml
      - name: Install latest Rust nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-01-01
          override: true
      - name: Add target
        run: |
          rustup target add aarch64-unknown-linux-gnu
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Prepare maturin publish
        shell: bash
        run: |
          rm py-polars/README.md
          cp README.md py-polars/README.md
          cd py-polars
          rustup override set nightly-2022-01-01
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      - name: maturin publish
        uses: messense/maturin-action@v1
        env:
          MATURIN_PASSWORD: ${{ secrets.PYPI_PASS }}
        with:
          target: aarch64-unknown-linux-gnu
          maturin-version: 0.12.1
          command: publish
          args: -m py-polars/Cargo.toml --no-sdist -o wheels -i python -u ritchie46 
```
