### ISSUE TITLE
Fail to build on target aarch64

### ISSUE THREAD

**Issue by binh-vu** [messense/maturin-action#49]
Hi,

I try to build python extension with different platforms ([test project](https://github.com/binh-vu/rust-python-template)). However, I encounter an error when trying to build on non x86_64 and x64:

```bash
Run messense/maturin-action@v1
  with:
    manylinux: auto
    target: aarch6[4](https://github.com/binh-vu/rust-python-template/runs/7050414502?check_suite_focus=true#step:3:4)
    command: build
    args: --release -o dist
    maturin-version: latest

Caused by: Couldn't find any python interpreters. Please specify at least one with -i
```

This is the build configuration that leads to the error:

```yaml
jobs:
  linux:
    strategy:
      matrix:
        target: [aarch64]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: messense/maturin-action@v1
        with:
          manylinux: auto
          target: ${{ matrix.target }}
          command: build
          args: --release -o dist
```

The error message seems straightforward, I only need to supply the python version via `-i`. Checking some of your examples, I found that by providing `-i 3.8`, it found and used the one at `/usr/bin/python3.8`. The behavior seems odd to me since it couldn't find any interpreters before.

However, when I dug deeper, I think I found in the Docker image used to build, `/usr/bin/python3.8` may be not the one in the target architecture. I ran this command: `/usr/bin/python3.8 -c 'import platform; print(platform.machine())'` and it printed: x86_64. Checking the [Dockerfile](https://github.com/messense/manylinux-cross/blob/main/manylinux2014/aarch64/Dockerfile)), I notice that the python built for aarch64 architecture is copied to [`/opt/python`](https://github.com/messense/manylinux-cross/blob/83ae932351b5dfdccadd5d6f07d99f6bae3c4569/manylinux2014/aarch64/Dockerfile#L146) and while the image that `/usr/bin/python3.8` is built from `ubuntu:20.04`.

So, I think `/usr/bin/python3.8` may not be the correct python. How can I specify the interpreter I want in `/opt/python` to maturin? I tried: `-i /opt/python/cp38-cp38/bin/python` but it doesn't work (`Invalid python interpreter version`)

Thank you
