### ISSUE TITLE
Setting "target" and "manylinux" to build musl only builds python3.8 wheels

### ISSUE THREAD

**Issue by tgross35** [messense/maturin-action#56]
I haven't been able to figure out what exactly causes this, but in this example configuration:

```yaml
    - uses: messense/maturin-action@v1
      with:
        manylinux: auto
        command: build
        args: --release -o dist --manifest-path crates/stringmetrics_py/Cargo.toml
    # NOTE: Seems to only build musl wheels for cpython 3.8
    - uses: messense/maturin-action@v1
      with:
        target: x86_64-unknown-linux-musl
        manylinux: musllinux_1_1
        command: build
        args: --release -o dist --manifest-path crates/stringmetrics_py/Cargo.toml
```

The first step generates wheels for 3.7-3.10 as expected, but the second only does 3.8.
