### ISSUE TITLE
Maturin failed to find python interpreter

### ISSUE THREAD

**Issue by ritchie46** [messense/maturin-action#71]
When setting `manylinux=auto` or (lower than 2_24), the pipeline fails as it cannot find a python interpreter.

This is the yaml snippet:

```yaml
  build_manylinux:
    name: Create Release manylinux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Prepare maturin publish
        shell: bash
        run: |
          rm py-polars/README.md
          cp README.md py-polars/README.md

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
          architecture: x64

      - name: publish x64_64
        uses: messense/maturin-action@v1
        env:
          MATURIN_PASSWORD: ${{ secrets.PYPI_PASS }}
          RUSTFLAGS: '-C target-feature=+fxsr,+sse,+sse2,+sse3,+ssse3,+sse4.1,+sse4.2,+popcnt,+avx,+fma'
        with:
          rust-toolchain: nightly-2022-08-22
          maturin-version: '0.13.0'
          command: publish
          args: -m py-polars/Cargo.toml --skip-existing -o wheels -i python -u ritchie46
```
This is the error in question:
```
Run messense/maturin-action@v1
Pull Docker image
Cleanup build scripts artifact directory
/usr/bin/docker run --rm --workdir /home/runner/work/polars/polars -e DEBIAN_FRONTEND=noninteractive -e ARCHFLAGS -e _PYTHON_SYSCONFIGDATA_NAME -e MATURIN_PASSWORD -e RUSTFLAGS -v /home/runner/work/polars/polars:/home/runner/work/polars/polars quay.io/pypa/manylinux2014_x86_64:latest /home/runner/work/polars/polars/run-maturin-action.sh
Install Rust
Install maturin
📦 Including license file "py-polars/LICENSE"
🍹 Building a mixed python/rust project
🔗 Found pyo3 bindings with abi3 support for Python ≥ 3.7
🐍 Not using a specific python interpreter
💥 maturin failed
  Caused by: Failed to find any python interpreter
```
