### ISSUE TITLE
Action fails on Windows and macos when using `--cargo-extra-args="--features python"`

### ISSUE THREAD

**Issue by g-bauer** [messense/maturin-action#9]
I want to build my wheels using maturin-action in a mixed rust-python library. The `python` feature enables the python part of the crate. When providing `cargo-extra-args` to `args`, the action works on linux but fails on windows and macos.

```yml
      - name: Build Wheels
        uses: messense/maturin-action@v1
        with:
          manylinux: auto
          command: build
          args: --release --out dist --no-sdist --cargo-extra-args="--features python"
``` 

Without the `--cargo-extra-args` argument (using `python` as default feature) it works on all platforms.
