### ISSUE TITLE
linking with 'cc' cannot find -lpythonXX

### ISSUE THREAD

**Issue by dpgraham4401** [messense/maturin-action#93]
Hi and first, thank you for this project, it's been extremely helpful!

I'm hoping you can help me out with the following error i get using the maturin-action. I've got a [stripped down project](https://github.com/dpgraham4401/quil) that I'm using as a proof of concept to see. It only contains the [Using Python from Rust example](https://github.com/PyO3/pyo3#using-python-from-rust) from pyo3, and pyproject.toml from `maturin new -b bin` command.

I continue to receive the following error when building for linux (building MacOS universal2 wheels also has problems, windows wheels build fine) I also don't have this problem building wheels on the desktop (both on linux X86_64 and MacOS arm64) 

```console
error: linking with `cc` failed: exit status: 1
...
/opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: cannot find -lpython3.XX # where XX is the python version
```
full logs here https://github.com/dpgraham4401/quil/actions/runs/3345795050

I figure this is user error, is there something in pyo3/maturins/maturin-actions documentation that I'm missing or is building wheels this way not a supported feature?

The full workflow file can be found [here](https://github.com/dpgraham4401/quil/actions/runs/3345795050/workflow), this is the linux job based on the examples in maturin-action's README. 
```yaml
jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [ x86_64 ]
        py-version: ['3.9', '3.10']
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.py-version }}

      - name: build wheels
        uses: messense/maturin-action@v1
        with:
          target: ${{ matrix.target }}
          manylinux: auto
          maturin-version: latest
          args: --release -i ${{ matrix.py-version }} --out dist

```
