### ISSUE TITLE
messense/manylinux2014-cross g++ does not recognize c++17 flag

### ISSUE THREAD

**Issue by Congyuwang** [messense/maturin-action#96]
Using container

```
      - name: Build Wheels
        uses: messense/maturin-action@v1
        with:
          rust-toolchain: stable
          rustup-components: rustfmt
          target: ${{ matrix.target }}
          manylinux: 2014
          args: --release --out dist --interpreter '3.7 3.8 3.9 3.10 3.11'
          container: messense/manylinux2014-cross:${{ matrix.target }}
```

Got warning

 `warning: x86_64-unknown-linux-gnu-g++: error: unrecognized command line option '-std=c++17'`.

Does it mean that a newer version of g++ is needed?
